### ISSUE TITLE
コマンド検索時の検索結果に対しての翻訳

### ISSUE THREAD

**Issue by nibushibu** [junkawa/figma_jp#1]
素晴らしい拡張をありがとうございます！👍

`⌘（Windowsの場合は Ctrl）+ /` で開く、コマンドの検索をした時の、
検索結果については、日本語にはならないようだったのですが、
その部分まで翻訳を反映させることって、そもそも可能でしょうか…？

**Comment by junkawa** [comment]
@nibushibu さん、テストしていただきありがとうございます！

コマンド検索の日本語化についてですが、現状、下記の認識です。

　1) 英語で検索し、結果を日本語で表示　→　おそらく実現可能。表示速度がネックになりそう。

　2) 日本語で検索する　→　要検討、難しそうです

ご希望の動作は、1) 、2) のどちらでしょうか？

**Comment by nibushibu** [comment]
@junkawa 早々に回答ありがとうございます！

私が日本語で使うとしたら理想的には 2）を期待するだろうなと思いました。

ただ、質問しておきながら、自分も原理的に難しそうだなとは思っていたので(汗)
現実的には 1）をやるかどうか、という話になると思うんですが、
1）だと、検索してる文字と結果が結びつかないので、個人的にはそもそもやらないほうがいいのかなという気がしました…（表示速度にも影響するとのことですし…）

使う人が理解していればいい話かなという気がするので、コマンドの検索結果は翻訳対象外、と予めと明記しちゃえばいいのかもしれませんね！

ひとまず、僕の質問については回答頂けたので、この Issue 自体は Close させていただきます！
回答ありがとうございます！

**Comment by junkawa** [comment]
@nibushibu 承知しました！

翻訳対象外を予め明記するアイデアを使わせていただきます😀
